name: 🚀 Deploy Native PHP BOXRETAIL to Shared Hosting (public_html)

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    name: Fast Deploy to public_html via FTP
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🚀 Deploy Native PHP App to public_html via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/
          local-dir: ./public_html_package/
          dangerous-clean-slate: false
